### ISSUE TITLE
AV False Positive?

### ISSUE THREAD

**Issue by The-Artificer** [nikidziuba/PSE#1]
Acquired from: https://www.nexusmods.com/phasmophobia/mods/81?tab=description

AV Result:
https://www.virustotal.com/gui/file/d5a013df40b3445b264c28815ca332f98d4ae45c591f09aed488f20e8a4424dd/detection

**Comment by nikidziuba** [comment]
Yes, that's right. I totally forgot about this project and there have been reports of corrupting save files so I'm making it archived.
